### ISSUE TITLE
Is the name field redundant?

### ISSUE THREAD

**Issue by matthias-t** [matthias-t/workspace#44]
It's useless to serialize the workspace names into the TOML files, since the name sets their file name and is used to read workspaces. What is supposed to happen if you have `~/.workspace/workspace-one.toml` containing:
```toml
name = "workspace-two"
path = "~/what/ever"
```
